name: PVP
version: '1.0-SNAPSHOT'
main: org.desp.pVP.PVP
api-version: '1.20'
depend: [MMOItems, MythicLib, MongoLibraryPlugin, MMOMail, MMOCore, BinggreAPI]
commands:
  대전:
    aliases: ["eowjs"]
#  전적확인:
#    aliases: ["wjswjrghkrdls"]